spring:
#  application:
#    name: hello-spring-cloud-zipkin
  # config client 云配置
  cloud:
    config:
      uri: http://localhost:8888
      name: zuul
      label: devlop
      profile: prod  # 加载dev文件

  #解决The bean 'characterEncodingFilter', defined in class path resource....
#  main:
#    allow-bean-definition-overriding: true

#server:
#  port: 9411 # 默认端口

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8887/eureka/

#解决IllegalArgumentException: Prometheus requires that all......
#management:
#  metrics:
#    web:
#      server:
#        auto-time-requests: false