spring:
  application:
    name: hello-spring-cloud-zipkin
  # config client 云配置
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: zuul
#      label: devlop
#      profile: dev  # 加载dev文件

server:
  port: 9411 # 默认端口

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8887/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false