spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: devlop # 仓库
      server:
        git:
          uri: https://github.com/liaoshenghuan/spring-cloud-config # 开发是使用内网地址
          search-paths: respo # 查找的路径
          username: liaoshenghuan
          password: huan10086......

server:
  # 此服务端口不可更改，需要更改是只能去bootstrap.properties文件里做更改
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8886/eureka/