spring:
#  application:
#    name: hello-spring-cloud-eureka
#
#  # 服务追踪配置
#  zipkin:
#    base-url: http://localhost:9411

  # config client 云配置
  cloud:
    config:
      uri: http://localhost:8888
      name: eureka
      label: devlop
      profile: prod  # 加载dev文件


#server:
#  port: 8886
#
#eureka:
#  instance:
#    hostname: localhost
#    #设置为IP访问时需要做以下配置
##    perferIpAddress: true
#  client:
#    #以下两个属性是用来区分是否服务端，不写两个属性就是客户端
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/