spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  # 用来模拟UI层配置
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  # 服务追踪配置
  zipkin:
    base-url: http://localhost:9411
  # config client 云配置
  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-feign
      label: devlop
      profile: prod  # 加载dev文件

# 以下为本地配置，启用云配置后删除
#server:
#  port: 8880
#
## feign 自带熔断器，默认是关闭的，需要再配置打开，配置如下
#feign:
#  hystrix:
#    enabled: true
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8886/eureka/


