spring:
  application:
    name: hello-spring-cloud-service-admin
  # config client 云配置
  cloud:
    config:
      uri: http://localhost:8888
      name: service-admin
      label: devlop
      profile: dev  # 加载dev文件


#server:
#  port: 8885
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8886/eureka/