spring:
#  application:
#    name: hello-spring-cloud-web-admin-ribbon
#  # 用来模拟UI层配置
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#
#

  # config client 云配置
  cloud:
    config:
      uri: http://localhost:8888
      name: web-admin-ribbon
      label: devlop
      profile: prod  # 加载dev文件

#server:
#  port: 8881
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8886/eureka/